# Define your Workflow name here
name: Hello World Workflow

# on is a triggering event that when to run the workflow, Here on.push is the signal whenver there is a push to the repo on main branch run this workflow.
on:
  push: 
    branches:
      - main
  # similiarly whenver there is a pull request happens on the repo it should run the workflow, this is useful to review the changes before merging.
  # Ex -
  # pull_request:
  #     branches:
  #         - main

# Create a new Job (Set of steps that will run on env)
jobs:
  # Name of Job
  say-hello:
    # Intiate a environment in which our steps will run
    runs-on: ubuntu-latest
    # Steps (set of commands that will run)
    steps:
        # There can be multiple steps
      - name: Checkout Code
        # Actions are the custome pre-defined tools which we can use. Here "use: actions/checkout@v4" pulls our code into the VM so we can work with it.
        uses: actions/checkout@v4
        # Name of first step 
      - name: hello-world
        # Run this command
        run: echo "Hello World" 
  # Now there can be Multiple Jobs running parallel or sequentially
  # Here is the Job which will run in parallel
  list-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: list files
        run: ls -la
  # Another Job to run
  env-test:
    runs-on: ubuntu-latest
    # We can set env variables which can be send to the steps to execute
    env:
      MY_NAME: "Alex"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use env variable
        # Here GITHUB_SHA  is the built in variable for commit hash
        run: echo "Hi my name is $MY_NAME! commit- $GITHUB_SHA"
  # Test js/typescript applications
  # node-js-test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # actions/setup-node@v4 will setup nodejs for the code review
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        # with helps woth setup the which node version to use
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: run test
        run: npm test
        
